version: '3.9'

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: weather
      POSTGRES_USER: weather
      POSTGRES_PASSWORD: weather
    volumes:
      - postgres_data:/var/lib/postgresql/data

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/Weather_Website
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DATABASE_NAME=weather
      - DATABASE_USER=weather
      - DATABASE_PASSWORD=weather
      - DATABASE_HOST=db
      - DATABASE_PORT=5432

volumes:
  postgres_data:
